apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shanghai-deployment
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: shanghai
    spec:
      containers:
      - name: shanghai
        image: asia.gcr.io/boxp-kt/shanghai:latest
        ports:
        - containerPort: 80
