apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shanghai
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: shanghai
    spec:
      containers:
      - name: shanghai
        image: asia.gcr.io/boxp-tk/shanghai:latest
        ports:
        - containerPort: 80
