apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shanghai
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: shanghai
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - shanghai
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: shanghai
        image: gcr.io/${PROJECT_ID}/shanghai:${REVISION_ID}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
