apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: shanghai
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
    # kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - boxp.tk
    - www.boxp.tk
    - atnd.boxp.tk
    - blog.boxp.tk
    secretName: shanghai-tls
  rules:
  - host: boxp.tk
    http:
      paths:
      - path: /*
        backend:
          serviceName: shanghai
          servicePort: 80
  - host: www.boxp.tk
    http:
      paths:
      - path: /*
        backend:
          serviceName: shanghai
          servicePort: 80
  - host: atnd.boxp.tk
    http:
      paths:
      - path: /*
        backend:
          serviceName: eure-atnd
          servicePort: 80
